server:
  port: 8081

spring:
  application:
    name: Inkspire-UserService

  datasource:
    url: jdbc:postgresql://localhost:5432/inkspire_user_db
    username: postgres
    password: Psql#0111

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: LevZH5wwRH6O6E9QRwwdPD4OqTCZ84opgnF++duOvRk=
